name: build

on:
  workflow_dispatch: {}
  pull_request:
    branches: ['**']

env:
  BUN_VERSION: 1.0.30

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: Lint with Biome
        run: bun run lint
      - name: Test with Bun
        run: bun test
